USE DATABASE CRICKET_ANALYTICS_DB;
USE SCHEMA DW;

CREATE OR REPLACE FUNCTION CRICKET_RUN_RATE(RUNS NUMBER, OVERS FLOAT)
RETURNS FLOAT
LANGUAGE SQL
AS
$$
  IFF(OVERS = 0, 0, RUNS / OVERS)
$$;

CREATE OR REPLACE FUNCTION CRICKET_BATTING_STRIKE_RATE(RUNS NUMBER, BALLS NUMBER)
RETURNS FLOAT
LANGUAGE SQL
AS
$$
  IFF(BALLS = 0, 0, (RUNS * 100.0) / BALLS)
$$;

CREATE OR REPLACE PROCEDURE REFRESH_CRICKET_AUDIT()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO CRICKET_ANALYTICS_DB.OPS.LOAD_AUDIT(OBJECT_NAME,ROW_COUNT,STATUS,MESSAGE)
  SELECT 'FACT_DELIVERY',COUNT(*),'SUCCESS','Audit refreshed'
  FROM CRICKET_ANALYTICS_DB.DW.FACT_DELIVERY;
  RETURN 'SUCCESS';
END;
$$;
