USE DATABASE CRICKET_ANALYTICS_DB;
CREATE OR REPLACE TABLE RAW.JSON_LAB (RAW_FILE VARIANT);

INSERT INTO RAW.JSON_LAB SELECT PARSE_JSON('{
  "player":"Virat Kohli",
  "teams":["RCB","India"],
  "stats":{"runs":100,"format":"T20"}
}');

SELECT RAW_FILE:player::STRING AS PLAYER,
       RAW_FILE:stats:runs::NUMBER AS RUNS,
       f.value::STRING AS TEAM
FROM RAW.JSON_LAB,
LATERAL FLATTEN(INPUT=>RAW_FILE:teams) f;
