version: 2

sources:
  - name: cricket_raw
    database: CRICKET_ANALYTICS
    schema: RAW
    tables:
      - name: RAW_TEAMS
      - name: RAW_PLAYERS
      - name: RAW_MATCHES
      - name: RAW_DELIVERIES
