-- Cricket Analytics: database, schemas and warehouses
CREATE DATABASE IF NOT EXISTS CRICKET_ANALYTICS_DB;

CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS_DB.RAW;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS_DB.DW;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS_DB.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS_DB.OPS;

CREATE WAREHOUSE IF NOT EXISTS CRICKET_ETL_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS CRICKET_BI_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE CRICKET_ETL_WH;
USE DATABASE CRICKET_ANALYTICS_DB;
