USE DATABASE CRICKET_ANALYTICS_DB;
USE SCHEMA DW;

CREATE OR REPLACE TABLE DIM_DATE (
  SK_DATE NUMBER PRIMARY KEY, DATE_VALUE DATE, YEAR NUMBER, QUARTER NUMBER,
  MONTH NUMBER, WEEK_OF_YEAR NUMBER, IS_WEEKEND BOOLEAN
);

INSERT INTO DIM_DATE
SELECT TO_NUMBER(TO_CHAR(D,'YYYYMMDD')),D,YEAR(D),QUARTER(D),MONTH(D),WEEKOFYEAR(D),
       DAYOFWEEKISO(D) IN (6,7)
FROM (
  SELECT DATEADD(DAY,SEQ4(),'2020-01-01'::DATE) D
  FROM TABLE(GENERATOR(ROWCOUNT=>4018))
);

CREATE OR REPLACE TABLE DIM_TEAM (
  SK_TEAM NUMBER AUTOINCREMENT, TEAM_ID VARCHAR, TEAM_NAME VARCHAR, TEAM_CODE VARCHAR,
  COUNTRY VARCHAR, COMPETITION VARCHAR, REGION VARCHAR, ESTABLISHED_DATE DATE, STATUS VARCHAR
);

INSERT INTO DIM_TEAM (TEAM_ID,TEAM_NAME,TEAM_CODE,COUNTRY,COMPETITION,REGION,ESTABLISHED_DATE,STATUS)
SELECT TEAM_ID,TEAM_NAME,TEAM_CODE,COUNTRY,COMPETITION,REGION,ESTABLISHED_DATE,STATUS
FROM RAW.RAW_TEAMS;

CREATE OR REPLACE TABLE DIM_VENUE (
  SK_VENUE NUMBER AUTOINCREMENT, VENUE_ID VARCHAR, VENUE_NAME VARCHAR,
  CITY VARCHAR, STATE VARCHAR, COUNTRY VARCHAR, REGION VARCHAR, STATUS VARCHAR
);

INSERT INTO DIM_VENUE(VENUE_ID)
SELECT DISTINCT VENUE_ID FROM RAW.RAW_MATCHES WHERE VENUE_ID IS NOT NULL;

CREATE OR REPLACE TABLE DIM_PLAYER (
  SK_PLAYER NUMBER AUTOINCREMENT, PLAYER_ID VARCHAR, FIRST_NAME VARCHAR, LAST_NAME VARCHAR,
  NATIONALITY VARCHAR, BATTING_STYLE VARCHAR, BOWLING_STYLE VARCHAR, ROLE VARCHAR,
  CURRENT_TEAM_ID VARCHAR, CONTRACT_START DATE, STATUS VARCHAR,
  EFF_START_TS TIMESTAMP_NTZ, EFF_END_TS TIMESTAMP_NTZ, IS_CURRENT BOOLEAN, HASH_DIFF VARCHAR
);

INSERT INTO DIM_PLAYER
SELECT NULL, PLAYER_ID,FIRST_NAME,LAST_NAME,NATIONALITY,BATTING_STYLE,BOWLING_STYLE,ROLE,
       CURRENT_TEAM_ID,CONTRACT_START,STATUS,UPDATED_AT,'9999-12-31'::TIMESTAMP_NTZ,TRUE,
       MD5(CONCAT_WS('|',NATIONALITY,BATTING_STYLE,BOWLING_STYLE,ROLE,CURRENT_TEAM_ID))
FROM RAW.RAW_PLAYERS;

CREATE OR REPLACE TABLE DIM_MATCH (
  SK_MATCH NUMBER AUTOINCREMENT, MATCH_ID VARCHAR, COMPETITION VARCHAR, FORMAT VARCHAR,
  MATCH_DATE DATE, VENUE_ID VARCHAR, TEAM_A_ID VARCHAR, TEAM_B_ID VARCHAR,
  TOSS_WINNER_TEAM_ID VARCHAR, TOSS_DECISION VARCHAR, WINNER_TEAM_ID VARCHAR,
  RESULT_TYPE VARCHAR, RESULT_MARGIN NUMBER, MATCH_STATUS VARCHAR, UPDATED_AT TIMESTAMP_NTZ
);

INSERT INTO DIM_MATCH
SELECT NULL,MATCH_ID,COMPETITION,FORMAT,MATCH_DATE,VENUE_ID,TEAM_A_ID,TEAM_B_ID,
       TOSS_WINNER_TEAM_ID,TOSS_DECISION,WINNER_TEAM_ID,RESULT_TYPE,RESULT_MARGIN,MATCH_STATUS,UPDATED_AT
FROM RAW.RAW_MATCHES;

CREATE OR REPLACE TABLE FACT_DELIVERY (
  DELIVERY_ID VARCHAR PRIMARY KEY, SK_MATCH NUMBER, SK_DATE NUMBER,
  SK_BATTING_TEAM NUMBER, SK_BOWLING_TEAM NUMBER, SK_STRIKER NUMBER,
  SK_NON_STRIKER NUMBER, SK_BOWLER NUMBER, SK_VENUE NUMBER,
  INNINGS_NO NUMBER, OVER_NO NUMBER, BALL_NO NUMBER,
  BATSMAN_RUNS NUMBER, WIDES NUMBER, NO_BALLS NUMBER, BYES NUMBER, LEG_BYES NUMBER,
  TOTAL_RUNS NUMBER, IS_WICKET NUMBER, DISMISSAL_TYPE VARCHAR,
  IS_FOUR NUMBER, IS_SIX NUMBER, IS_DOT_BALL NUMBER, UPDATED_AT TIMESTAMP_NTZ
);

INSERT INTO FACT_DELIVERY
SELECT d.DELIVERY_ID,m.SK_MATCH,dt.SK_DATE,bt.SK_TEAM,bo.SK_TEAM,s.SK_PLAYER,ns.SK_PLAYER,bw.SK_PLAYER,
       v.SK_VENUE,d.INNINGS_NO,d.OVER_NO,d.BALL_NO,d.BATSMAN_RUNS,d.WIDES,d.NO_BALLS,d.BYES,d.LEG_BYES,
       d.TOTAL_RUNS,d.IS_WICKET,d.DISMISSAL_TYPE,d.IS_FOUR,d.IS_SIX,d.IS_DOT_BALL,d.UPDATED_AT
FROM RAW.RAW_DELIVERIES d
JOIN DIM_MATCH m ON m.MATCH_ID=d.MATCH_ID
JOIN DIM_DATE dt ON dt.DATE_VALUE=(SELECT MATCH_DATE FROM DIM_MATCH WHERE SK_MATCH=m.SK_MATCH)
LEFT JOIN DIM_TEAM bt ON bt.TEAM_ID=d.BATTING_TEAM_ID
LEFT JOIN DIM_TEAM bo ON bo.TEAM_ID=d.BOWLING_TEAM_ID
LEFT JOIN DIM_PLAYER s ON s.PLAYER_ID=d.STRIKER_PLAYER_ID AND s.IS_CURRENT
LEFT JOIN DIM_PLAYER ns ON ns.PLAYER_ID=d.NON_STRIKER_PLAYER_ID AND ns.IS_CURRENT
LEFT JOIN DIM_PLAYER bw ON bw.PLAYER_ID=d.BOWLER_PLAYER_ID AND bw.IS_CURRENT
LEFT JOIN DIM_VENUE v ON v.VENUE_ID=m.VENUE_ID;
