USE DATABASE CRICKET_ANALYTICS_DB;
USE SCHEMA SEMANTIC;

CREATE OR REPLACE VIEW V_MATCH_SUMMARY AS
SELECT m.MATCH_ID,m.COMPETITION,m.FORMAT,m.MATCH_DATE,m.VENUE_ID,
       m.TEAM_A_ID,m.TEAM_B_ID,m.WINNER_TEAM_ID,m.RESULT_TYPE,m.RESULT_MARGIN,
       COUNT(f.DELIVERY_ID) BALLS,
       SUM(f.TOTAL_RUNS) TOTAL_RUNS,
       SUM(f.IS_WICKET) WICKETS,
       SUM(f.IS_FOUR) FOURS,
       SUM(f.IS_SIX) SIXES,
       SUM(f.IS_DOT_BALL) DOT_BALLS
FROM DW.DIM_MATCH m
LEFT JOIN DW.FACT_DELIVERY f ON f.SK_MATCH=m.SK_MATCH
GROUP BY ALL;

CREATE OR REPLACE VIEW V_PLAYER_BATTING AS
SELECT p.PLAYER_ID,p.FIRST_NAME,p.LAST_NAME,p.ROLE,
       SUM(f.BATSMAN_RUNS) RUNS,
       COUNT_IF(f.BATSMAN_RUNS>0) SCORING_BALLS,
       SUM(f.IS_FOUR) FOURS,SUM(f.IS_SIX) SIXES,
       COUNT(f.DELIVERY_ID) BALLS
FROM DW.DIM_PLAYER p
JOIN DW.FACT_DELIVERY f ON f.SK_STRIKER=p.SK_PLAYER
WHERE p.IS_CURRENT
GROUP BY ALL;

CREATE OR REPLACE VIEW V_PLAYER_BOWLING AS
SELECT p.PLAYER_ID,p.FIRST_NAME,p.LAST_NAME,p.ROLE,
       SUM(f.TOTAL_RUNS-f.WIDES-f.LEG_BYES) RUNS_CONCEDED,
       SUM(f.IS_WICKET) WICKETS,
       COUNT(f.DELIVERY_ID) BALLS
FROM DW.DIM_PLAYER p
JOIN DW.FACT_DELIVERY f ON f.SK_BOWLER=p.SK_PLAYER
WHERE p.IS_CURRENT
GROUP BY ALL;

CREATE OR REPLACE VIEW V_TEAM_TRENDS AS
SELECT t.TEAM_ID,t.TEAM_NAME,t.COMPETITION,
       COUNT(DISTINCT m.MATCH_ID) MATCHES,
       COUNT_IF(m.WINNER_TEAM_ID=t.TEAM_ID) WINS
FROM DW.DIM_TEAM t
LEFT JOIN DW.DIM_MATCH m
  ON t.TEAM_ID IN (m.TEAM_A_ID,m.TEAM_B_ID)
GROUP BY ALL;
