USE DATABASE CRICKET_ANALYTICS_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT FF_CRICKET_CSV
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL', 'null');

CREATE OR REPLACE TABLE RAW_TEAMS (
  TEAM_ID VARCHAR, TEAM_NAME VARCHAR, TEAM_CODE VARCHAR, COUNTRY VARCHAR,
  COMPETITION VARCHAR, REGION VARCHAR, ESTABLISHED_DATE DATE, STATUS VARCHAR,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), SOURCE_FILE_NAME VARCHAR
);

CREATE OR REPLACE TABLE RAW_PLAYERS (
  PLAYER_ID VARCHAR, FIRST_NAME VARCHAR, LAST_NAME VARCHAR, NATIONALITY VARCHAR,
  BATTING_STYLE VARCHAR, BOWLING_STYLE VARCHAR, ROLE VARCHAR,
  CURRENT_TEAM_ID VARCHAR, CONTRACT_START DATE, STATUS VARCHAR,
  UPDATED_AT TIMESTAMP_NTZ, LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE_FILE_NAME VARCHAR
);

CREATE OR REPLACE TABLE RAW_MATCHES (
  MATCH_ID VARCHAR, COMPETITION VARCHAR, FORMAT VARCHAR, MATCH_DATE DATE,
  VENUE_ID VARCHAR, TEAM_A_ID VARCHAR, TEAM_B_ID VARCHAR,
  TOSS_WINNER_TEAM_ID VARCHAR, TOSS_DECISION VARCHAR, WINNER_TEAM_ID VARCHAR,
  RESULT_TYPE VARCHAR, RESULT_MARGIN NUMBER, MATCH_STATUS VARCHAR,
  UPDATED_AT TIMESTAMP_NTZ, LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE_FILE_NAME VARCHAR
);

CREATE OR REPLACE TABLE RAW_DELIVERIES (
  DELIVERY_ID VARCHAR, MATCH_ID VARCHAR, INNINGS_NO NUMBER, OVER_NO NUMBER,
  BALL_NO NUMBER, BATTING_TEAM_ID VARCHAR, BOWLING_TEAM_ID VARCHAR,
  STRIKER_PLAYER_ID VARCHAR, NON_STRIKER_PLAYER_ID VARCHAR, BOWLER_PLAYER_ID VARCHAR,
  BATSMAN_RUNS NUMBER, WIDES NUMBER, NO_BALLS NUMBER, BYES NUMBER, LEG_BYES NUMBER,
  TOTAL_RUNS NUMBER, IS_WICKET NUMBER, DISMISSAL_TYPE VARCHAR,
  IS_FOUR NUMBER, IS_SIX NUMBER, IS_DOT_BALL NUMBER, UPDATED_AT TIMESTAMP_NTZ,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), SOURCE_FILE_NAME VARCHAR
);
