USE DATABASE CRICKET_ANALYTICS_DB;

CREATE OR REPLACE VIEW OPS.V_DQ_RESULTS AS
SELECT 'RAW_TEAMS_DUPLICATES' CHECK_NAME, COUNT(*) BAD_ROWS
FROM (
  SELECT TEAM_ID FROM RAW.RAW_TEAMS GROUP BY TEAM_ID HAVING COUNT(*)>1
)
UNION ALL
SELECT 'RAW_PLAYERS_DUPLICATES',COUNT(*)
FROM (
  SELECT PLAYER_ID FROM RAW.RAW_PLAYERS GROUP BY PLAYER_ID HAVING COUNT(*)>1
)
UNION ALL
SELECT 'RAW_MATCHES_DUPLICATES',COUNT(*)
FROM (
  SELECT MATCH_ID FROM RAW.RAW_MATCHES GROUP BY MATCH_ID HAVING COUNT(*)>1
)
UNION ALL
SELECT 'RAW_DELIVERIES_DUPLICATES',COUNT(*)
FROM (
  SELECT DELIVERY_ID FROM RAW.RAW_DELIVERIES GROUP BY DELIVERY_ID HAVING COUNT(*)>1
)
UNION ALL
SELECT 'DELIVERIES_UNKNOWN_MATCH',COUNT(*)
FROM RAW.RAW_DELIVERIES d
LEFT JOIN RAW.RAW_MATCHES m ON m.MATCH_ID=d.MATCH_ID
WHERE m.MATCH_ID IS NULL;
