USE DATABASE CRICKET_ANALYTICS_DB;

CREATE ROLE IF NOT EXISTS CRICKET_ANALYST;
CREATE ROLE IF NOT EXISTS CRICKET_ETL;
CREATE ROLE IF NOT EXISTS CRICKET_INGEST;

GRANT USAGE ON DATABASE CRICKET_ANALYTICS_DB TO ROLE CRICKET_ANALYST;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS_DB.SEMANTIC TO ROLE CRICKET_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA CRICKET_ANALYTICS_DB.SEMANTIC TO ROLE CRICKET_ANALYST;

-- Example masking policy for player contract/start information.
CREATE OR REPLACE MASKING POLICY DW.PLAYER_CONTRACT_MASK
AS (VAL DATE) RETURNS DATE ->
  CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','CRICKET_ETL') THEN VAL
    ELSE NULL
  END;

ALTER TABLE DW.DIM_PLAYER
  MODIFY COLUMN CONTRACT_START
  SET MASKING POLICY DW.PLAYER_CONTRACT_MASK;
