USE DATABASE CRICKET_ANALYTICS_DB;

CREATE OR REPLACE STREAM RAW_DELIVERIES_STREAM
ON TABLE RAW.RAW_DELIVERIES
APPEND_ONLY=TRUE;

CREATE OR REPLACE TABLE OPS.LOAD_AUDIT (
  AUDIT_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  OBJECT_NAME VARCHAR, ROW_COUNT NUMBER, STATUS VARCHAR, MESSAGE VARCHAR
);

CREATE OR REPLACE TASK OPS.TASK_CRICKET_PIPELINE
  WAREHOUSE=CRICKET_ETL_WH
  SCHEDULE='USING CRON 0 * * * * UTC'
AS
  INSERT INTO OPS.LOAD_AUDIT(OBJECT_NAME,ROW_COUNT,STATUS,MESSAGE)
  SELECT 'RAW_DELIVERIES',COUNT(*),'RUNNING','Hourly pipeline audit'
  FROM RAW.RAW_DELIVERIES;

-- Resume only after validating the schedule and warehouse.
-- ALTER TASK OPS.TASK_CRICKET_PIPELINE RESUME;
