-- 00_setup.sql
CREATE DATABASE IF NOT EXISTS CRICKET_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS.DW;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS.SEM;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS.OPS;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS.CORTEX;

CREATE WAREHOUSE IF NOT EXISTS CRICKET_INGEST_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE WAREHOUSE IF NOT EXISTS CRICKET_DW_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE WAREHOUSE IF NOT EXISTS CRICKET_APP_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

USE DATABASE CRICKET_ANALYTICS;
CREATE FILE FORMAT IF NOT EXISTS RAW.CSV_FF TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' TRIM_SPACE=TRUE EMPTY_FIELD_AS_NULL=TRUE NULL_IF=('','NULL','null');
CREATE STAGE IF NOT EXISTS RAW.CRICKET_LANDING_STAGE FILE_FORMAT=RAW.CSV_FF COMMENT='Landing stage for cricket analytics feeds';
CREATE STAGE IF NOT EXISTS RAW.CRICKET_QUARANTINE_STAGE FILE_FORMAT=RAW.CSV_FF COMMENT='Quarantine location for rejected/bad files';
