-- 00_setup.sql
-- Snowflake foundation for the Cricket Analytics Platform.
CREATE DATABASE IF NOT EXISTS CRICKET_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS.BRONZE;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS.SILVER;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS.GOLD;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS.SEM;
CREATE SCHEMA IF NOT EXISTS CRICKET_ANALYTICS.OPS;

CREATE WAREHOUSE IF NOT EXISTS CRICKET_INGEST_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE WAREHOUSE IF NOT EXISTS CRICKET_ETL_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE WAREHOUSE IF NOT EXISTS CRICKET_APP_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

USE DATABASE CRICKET_ANALYTICS;

CREATE FILE FORMAT IF NOT EXISTS RAW.CSV_FF
  TYPE=CSV
  SKIP_HEADER=1
  FIELD_OPTIONALLY_ENCLOSED_BY='"'
  TRIM_SPACE=TRUE
  EMPTY_FIELD_AS_NULL=TRUE
  NULL_IF=('','NULL','null');

CREATE STAGE IF NOT EXISTS RAW.CRICKET_LANDING_STAGE
  FILE_FORMAT=RAW.CSV_FF
  COMMENT='Landing stage for cricket analytics feeds';

CREATE STAGE IF NOT EXISTS RAW.CRICKET_QUARANTINE_STAGE
  FILE_FORMAT=RAW.CSV_FF
  COMMENT='Quarantine stage for invalid cricket feed files';
