-- 02_snowpipe.sql
USE DATABASE CRICKET_ANALYTICS;

-- One pipe per source entity. Pipes use ON_ERROR=CONTINUE so a bad row does not
-- stop the feed; rejected files/rows are handled by OPS validation and quarantine.
CREATE OR REPLACE PIPE RAW.PIPE_RAW_TEAMS AUTO_INGEST=TRUE AS
COPY INTO RAW.RAW_TEAMS
FROM (
    SELECT $1,$2,$3,$4,$5,$6,TRY_TO_DATE($7),$8,
           METADATA$START_SCAN_TIME,METADATA$FILENAME,METADATA$FILE_ROW_NUMBER
    FROM @RAW.CRICKET_LANDING_STAGE/teams/
)
FILE_FORMAT=(FORMAT_NAME=RAW.CSV_FF)
ON_ERROR=CONTINUE;

CREATE OR REPLACE PIPE RAW.PIPE_RAW_PLAYERS AUTO_INGEST=TRUE AS
COPY INTO RAW.RAW_PLAYERS
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,TRY_TO_DATE($9),$10,
           TRY_TO_TIMESTAMP_NTZ($11),METADATA$START_SCAN_TIME,
           METADATA$FILENAME,METADATA$FILE_ROW_NUMBER
    FROM @RAW.CRICKET_LANDING_STAGE/players/
)
FILE_FORMAT=(FORMAT_NAME=RAW.CSV_FF)
ON_ERROR=CONTINUE;

CREATE OR REPLACE PIPE RAW.PIPE_RAW_MATCHES AUTO_INGEST=TRUE AS
COPY INTO RAW.RAW_MATCHES
FROM (
    SELECT $1,$2,$3,TRY_TO_DATE($4),$5,$6,$7,$8,$9,$10,$11,
           TRY_TO_NUMBER($12),$13,TRY_TO_TIMESTAMP_NTZ($14),
           METADATA$START_SCAN_TIME,METADATA$FILENAME,METADATA$FILE_ROW_NUMBER
    FROM @RAW.CRICKET_LANDING_STAGE/matches/
)
FILE_FORMAT=(FORMAT_NAME=RAW.CSV_FF)
ON_ERROR=CONTINUE;

CREATE OR REPLACE PIPE RAW.PIPE_RAW_DELIVERIES AUTO_INGEST=TRUE AS
COPY INTO RAW.RAW_DELIVERIES
FROM (
    SELECT $1,$2,TRY_TO_NUMBER($3),TRY_TO_NUMBER($4),TRY_TO_NUMBER($5),
           $6,$7,$8,$9,$10,TRY_TO_NUMBER($11),TRY_TO_NUMBER($12),
           TRY_TO_NUMBER($13),TRY_TO_NUMBER($14),TRY_TO_NUMBER($15),
           TRY_TO_NUMBER($16),TRY_TO_NUMBER($17),$18,TRY_TO_NUMBER($19),
           TRY_TO_NUMBER($20),TRY_TO_NUMBER($21),TRY_TO_TIMESTAMP_NTZ($22),
           METADATA$START_SCAN_TIME,METADATA$FILENAME,METADATA$FILE_ROW_NUMBER
    FROM @RAW.CRICKET_LANDING_STAGE/deliveries/
)
FILE_FORMAT=(FORMAT_NAME=RAW.CSV_FF)
ON_ERROR=CONTINUE;

-- If the stage is populated manually, trigger ingestion with:
-- ALTER PIPE RAW.PIPE_RAW_TEAMS REFRESH;
-- ALTER PIPE RAW.PIPE_RAW_PLAYERS REFRESH;
-- ALTER PIPE RAW.PIPE_RAW_MATCHES REFRESH;
-- ALTER PIPE RAW.PIPE_RAW_DELIVERIES REFRESH;

-- For cloud auto-ingest, configure the appropriate notification integration and
-- cloud event notification outside this SQL file, then set the pipe notification.
