-- 05_semantic.sql
-- Thin semantic layer over dbt Gold/Silver objects. Applications query SEM only.
USE DATABASE CRICKET_ANALYTICS;

CREATE OR REPLACE VIEW SEM.V_MATCH_SUMMARY AS
SELECT * FROM GOLD.MATCH_OVERVIEW;

CREATE OR REPLACE VIEW SEM.V_PLAYER_BATTING AS
SELECT SK_PLAYER, PLAYER_ID, FIRST_NAME || ' ' || LAST_NAME AS PLAYER_NAME,
       RUNS, FOURS, SIXES, FOURS + SIXES AS BOUNDARIES,
       BALLS_FACED AS BALLS, STRIKE_RATE
FROM GOLD.PLAYER_INSIGHTS
WHERE PLAYER_ID <> 'UNKNOWN';

CREATE OR REPLACE VIEW SEM.V_PLAYER_BOWLING AS
SELECT p.SK_PLAYER, p.PLAYER_ID, p.FIRST_NAME || ' ' || p.LAST_NAME AS PLAYER_NAME,
       p.WICKETS, p.RUNS_CONCEDED, COALESCE(b.BALLS_BOWLED, 0) AS BALLS_BOWLED,
       p.ECONOMY
FROM GOLD.PLAYER_INSIGHTS p
LEFT JOIN (
    SELECT SK_BOWLER AS SK_PLAYER, COUNT(*) AS BALLS_BOWLED
    FROM SILVER.FACT_DELIVERY
    GROUP BY SK_BOWLER
) b ON b.SK_PLAYER = p.SK_PLAYER
WHERE p.PLAYER_ID <> 'UNKNOWN';

CREATE OR REPLACE VIEW SEM.V_TEAM_TRENDS AS
SELECT t.TEAM_ID, t.TEAM_NAME, m.MATCH_ID, m.MATCH_DATE,
       m.COMPETITION, m.FORMAT,
       CASE WHEN m.TEAM_A_ID = t.TEAM_ID THEN 'HOME'
            WHEN m.TEAM_B_ID = t.TEAM_ID THEN 'AWAY'
            ELSE 'UNKNOWN' END AS TEAM_SIDE,
       IFF(m.WINNER_TEAM_ID = t.TEAM_ID, 'WON', 'NOT_WON') AS RESULT,
       IFF(m.WINNER_TEAM_ID = t.TEAM_ID, 1, 0) AS WIN_FLAG,
       SUM(f.TOTAL_RUNS) AS RUNS,
       SUM(f.IS_WICKET) AS WICKETS
FROM SILVER.FACT_DELIVERY f
JOIN SILVER.DIM_TEAM t ON f.SK_BATTING_TEAM = t.SK_TEAM
JOIN SILVER.DIM_MATCH m ON f.SK_MATCH = m.SK_MATCH
WHERE t.TEAM_ID <> 'UNKNOWN'
GROUP BY ALL;

CREATE OR REPLACE VIEW SEM.V_VENUE_TRENDS AS
SELECT v.VENUE_ID, v.VENUE_NAME, m.FORMAT, m.COMPETITION,
       SUM(f.TOTAL_RUNS) AS RUNS, SUM(f.IS_WICKET) AS WICKETS,
       COUNT(DISTINCT m.MATCH_ID) AS MATCHES
FROM SILVER.FACT_DELIVERY f
JOIN SILVER.DIM_VENUE v ON f.SK_VENUE = v.SK_VENUE
JOIN SILVER.DIM_MATCH m ON f.SK_MATCH = m.SK_MATCH
WHERE v.VENUE_ID <> 'UNKNOWN'
GROUP BY ALL;

CREATE OR REPLACE VIEW SEM.V_DELIVERY_EXPLORER AS
SELECT f.DELIVERY_ID, m.MATCH_ID, m.MATCH_DATE, m.FORMAT, m.COMPETITION,
       f.INNINGS_NO, f.OVER_NO, f.BALL_NO, f.OVER_PHASE,
       bt.TEAM_NAME AS BATTING_TEAM, bw.TEAM_NAME AS BOWLING_TEAM,
       sp.FIRST_NAME || ' ' || sp.LAST_NAME AS STRIKER,
       bp.FIRST_NAME || ' ' || bp.LAST_NAME AS BOWLER,
       f.BATSMAN_RUNS, f.WIDES, f.NO_BALLS, f.BYES, f.LEG_BYES,
       f.TOTAL_RUNS, f.IS_WICKET, f.DISMISSAL_TYPE,
       f.IS_FOUR, f.IS_SIX, f.IS_DOT_BALL
FROM SILVER.FACT_DELIVERY f
JOIN SILVER.DIM_MATCH m ON f.SK_MATCH = m.SK_MATCH
JOIN SILVER.DIM_TEAM bt ON f.SK_BATTING_TEAM = bt.SK_TEAM
JOIN SILVER.DIM_TEAM bw ON f.SK_BOWLING_TEAM = bw.SK_TEAM
JOIN SILVER.DIM_PLAYER sp ON f.SK_STRIKER = sp.SK_PLAYER
JOIN SILVER.DIM_PLAYER bp ON f.SK_BOWLER = bp.SK_PLAYER;
