-- 05_semantic.sql
USE DATABASE CRICKET_ANALYTICS;
CREATE OR REPLACE VIEW SEM.V_MATCH_SUMMARY AS
SELECT m.MATCH_ID,m.COMPETITION,m.FORMAT,m.MATCH_DATE,m.VENUE_ID,m.TEAM_A_ID,m.TEAM_B_ID,m.WINNER_TEAM_ID,m.RESULT_TYPE,m.RESULT_MARGIN,f.INNINGS_NO,SUM(f.TOTAL_RUNS) TOTAL_RUNS,SUM(f.IS_WICKET) WICKETS,COUNT(*) BALLS,SUM(f.IS_FOUR) FOURS,SUM(f.IS_SIX) SIXES,SUM(f.IS_DOT_BALL) DOT_BALLS,SUM(f.WIDES+f.NO_BALLS+f.BYES+f.LEG_BYES) EXTRAS,ROUND(SUM(f.TOTAL_RUNS)/NULLIF(COUNT(*),0)*6,2) RUN_RATE,ROUND((SUM(f.IS_FOUR)+SUM(f.IS_SIX))*100.0/NULLIF(COUNT(*),0),2) BOUNDARY_PCT,ROUND(SUM(f.IS_DOT_BALL)*100.0/NULLIF(COUNT(*),0),2) DOT_BALL_PCT
FROM DW.FACT_DELIVERY f JOIN DW.DIM_MATCH m ON f.SK_MATCH=m.SK_MATCH GROUP BY ALL;

CREATE OR REPLACE VIEW SEM.V_PLAYER_BATTING AS
SELECT p.PLAYER_ID,p.FIRST_NAME||' '||p.LAST_NAME PLAYER_NAME,SUM(f.BATSMAN_RUNS) RUNS,SUM(f.IS_FOUR) FOURS,SUM(f.IS_SIX) SIXES,SUM(f.IS_FOUR)+SUM(f.IS_SIX) BOUNDARIES,COUNT(*) BALLS,ROUND(SUM(f.BATSMAN_RUNS)*100.0/NULLIF(COUNT(*),0),2) STRIKE_RATE
FROM DW.FACT_DELIVERY f JOIN DW.DIM_PLAYER p ON f.SK_STRIKER=p.SK_PLAYER WHERE p.PLAYER_ID<>'UNKNOWN' GROUP BY p.PLAYER_ID,p.FIRST_NAME,p.LAST_NAME;

CREATE OR REPLACE VIEW SEM.V_PLAYER_BOWLING AS
SELECT p.PLAYER_ID,p.FIRST_NAME||' '||p.LAST_NAME PLAYER_NAME,SUM(f.IS_WICKET) WICKETS,SUM(f.TOTAL_RUNS-f.BYES-f.LEG_BYES) RUNS_CONCEDED,COUNT(*) BALLS,ROUND(SUM(f.TOTAL_RUNS-f.BYES-f.LEG_BYES)*6.0/NULLIF(COUNT(*),0),2) ECONOMY
FROM DW.FACT_DELIVERY f JOIN DW.DIM_PLAYER p ON f.SK_BOWLER=p.SK_PLAYER WHERE p.PLAYER_ID<>'UNKNOWN' GROUP BY p.PLAYER_ID,p.FIRST_NAME,p.LAST_NAME;

CREATE OR REPLACE VIEW SEM.V_TEAM_TRENDS AS
SELECT t.TEAM_ID,t.TEAM_NAME,m.MATCH_ID,m.MATCH_DATE,m.COMPETITION,m.FORMAT,SUM(f.TOTAL_RUNS) RUNS,SUM(f.IS_WICKET) WICKETS
FROM DW.FACT_DELIVERY f JOIN DW.DIM_TEAM t ON f.SK_BATTING_TEAM=t.SK_TEAM JOIN DW.DIM_MATCH m ON f.SK_MATCH=m.SK_MATCH GROUP BY ALL;

CREATE OR REPLACE VIEW SEM.V_VENUE_TRENDS AS
SELECT v.VENUE_ID,v.VENUE_NAME,m.FORMAT,m.COMPETITION,SUM(f.TOTAL_RUNS) RUNS,SUM(f.IS_WICKET) WICKETS,COUNT(DISTINCT m.MATCH_ID) MATCHES
FROM DW.FACT_DELIVERY f JOIN DW.DIM_VENUE v ON f.SK_VENUE=v.SK_VENUE JOIN DW.DIM_MATCH m ON f.SK_MATCH=m.SK_MATCH GROUP BY ALL;

CREATE OR REPLACE VIEW SEM.V_DELIVERY_EXPLORER AS
SELECT f.DELIVERY_ID,m.MATCH_ID,m.MATCH_DATE,m.FORMAT,m.COMPETITION,f.INNINGS_NO,f.OVER_NO,f.BALL_NO,f.OVER_PHASE,bt.TEAM_NAME BATTING_TEAM,bw.TEAM_NAME BOWLING_TEAM,sp.FIRST_NAME||' '||sp.LAST_NAME STRIKER,bp.FIRST_NAME||' '||bp.LAST_NAME BOWLER,f.BATSMAN_RUNS,f.WIDES,f.NO_BALLS,f.BYES,f.LEG_BYES,f.TOTAL_RUNS,f.IS_WICKET,f.DISMISSAL_TYPE,f.IS_FOUR,f.IS_SIX,f.IS_DOT_BALL
FROM DW.FACT_DELIVERY f JOIN DW.DIM_MATCH m ON f.SK_MATCH=m.SK_MATCH JOIN DW.DIM_TEAM bt ON f.SK_BATTING_TEAM=bt.SK_TEAM JOIN DW.DIM_TEAM bw ON f.SK_BOWLING_TEAM=bw.SK_TEAM JOIN DW.DIM_PLAYER sp ON f.SK_STRIKER=sp.SK_PLAYER JOIN DW.DIM_PLAYER bp ON f.SK_BOWLER=bp.SK_PLAYER;
