-- 06_cortex.sql
USE DATABASE CRICKET_ANALYTICS;
CREATE TABLE IF NOT EXISTS CORTEX.RAG_DOCUMENTS (DOC_ID VARCHAR PRIMARY KEY,DOC_TYPE VARCHAR,TITLE VARCHAR,SEASON VARCHAR,RULE_SECTION VARCHAR,CONTENT VARCHAR,LOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE CORTEX SEARCH SERVICE CORTEX.CRICKET_KNOWLEDGE_SEARCH
  ON CONTENT
  ATTRIBUTES DOC_TYPE, SEASON, RULE_SECTION
  WAREHOUSE=CRICKET_APP_WH
  TARGET_LAG='1 hour'
  AS (SELECT DOC_ID,DOC_TYPE,TITLE,SEASON,RULE_SECTION,CONTENT FROM CORTEX.RAG_DOCUMENTS);
-- Cortex Analyst is exposed only through the curated SEM.V_* semantic objects.
-- See cortex/semantic_views/cricket_analytics.yaml.
