-- 07_security.sql
USE DATABASE CRICKET_ANALYTICS;

CREATE ROLE IF NOT EXISTS ROLE_INGEST;
CREATE ROLE IF NOT EXISTS ROLE_ETL;
CREATE ROLE IF NOT EXISTS ROLE_ANALYST;
CREATE ROLE IF NOT EXISTS ROLE_APP_STREAMLIT;
CREATE ROLE IF NOT EXISTS ROLE_ADMIN;

GRANT USAGE ON DATABASE CRICKET_ANALYTICS TO ROLE ROLE_INGEST, ROLE_ETL, ROLE_ANALYST, ROLE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA RAW TO ROLE ROLE_INGEST, ROLE_ETL;
GRANT USAGE ON SCHEMA BRONZE TO ROLE ROLE_ETL;
GRANT USAGE ON SCHEMA SILVER TO ROLE ROLE_ETL, ROLE_ANALYST, ROLE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA GOLD TO ROLE ROLE_ETL, ROLE_ANALYST, ROLE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA DW TO ROLE ROLE_ETL, ROLE_ANALYST;
GRANT USAGE ON SCHEMA SEM TO ROLE ROLE_ANALYST, ROLE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA OPS TO ROLE ROLE_ETL, ROLE_ADMIN;

GRANT SELECT ON ALL VIEWS IN SCHEMA SEM TO ROLE ROLE_ANALYST, ROLE_APP_STREAMLIT;
GRANT SELECT ON ALL VIEWS IN SCHEMA DW TO ROLE ROLE_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA GOLD TO ROLE ROLE_ANALYST, ROLE_APP_STREAMLIT;
GRANT SELECT ON ALL TABLES IN SCHEMA SILVER TO ROLE ROLE_ETL;
GRANT SELECT ON ALL VIEWS IN SCHEMA BRONZE TO ROLE ROLE_ETL;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA SEM TO ROLE ROLE_ANALYST, ROLE_APP_STREAMLIT;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DW TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOLD TO ROLE ROLE_ANALYST, ROLE_APP_STREAMLIT;

-- RAW is intentionally not granted to analyst/app roles.
-- Apply masking/row-access policies if sensitive columns are introduced.
