-- 07_security.sql
-- Role-based access control for the Cricket Analytics Platform.
-- Run with a role that can create roles and grant privileges.

USE ROLE ACCOUNTADMIN;
USE DATABASE CRICKET_ANALYTICS;

-- ============================================================
-- Roles
-- ============================================================
CREATE ROLE IF NOT EXISTS ROLE_INGEST;
CREATE ROLE IF NOT EXISTS ROLE_ETL;
CREATE ROLE IF NOT EXISTS ROLE_ANALYST;
CREATE ROLE IF NOT EXISTS ROLE_APP_STREAMLIT;
CREATE ROLE IF NOT EXISTS ROLE_ADMIN;

-- ============================================================
-- Database usage
-- ============================================================
GRANT USAGE ON DATABASE CRICKET_ANALYTICS TO ROLE ROLE_INGEST;
GRANT USAGE ON DATABASE CRICKET_ANALYTICS TO ROLE ROLE_ETL;
GRANT USAGE ON DATABASE CRICKET_ANALYTICS TO ROLE ROLE_ANALYST;
GRANT USAGE ON DATABASE CRICKET_ANALYTICS TO ROLE ROLE_APP_STREAMLIT;
GRANT USAGE ON DATABASE CRICKET_ANALYTICS TO ROLE ROLE_ADMIN;

-- ============================================================
-- Schema usage
-- ============================================================
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.RAW TO ROLE ROLE_INGEST;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.RAW TO ROLE ROLE_ETL;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.BRONZE TO ROLE ROLE_ETL;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.SILVER TO ROLE ROLE_ETL;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.SILVER TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.SILVER TO ROLE ROLE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.GOLD TO ROLE ROLE_ETL;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.GOLD TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.GOLD TO ROLE ROLE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.DW TO ROLE ROLE_ETL;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.DW TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.SEM TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.SEM TO ROLE ROLE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.OPS TO ROLE ROLE_ETL;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.OPS TO ROLE ROLE_ADMIN;

-- ============================================================
-- Warehouse usage
-- ============================================================
GRANT USAGE ON WAREHOUSE CRICKET_INGEST_WH TO ROLE ROLE_INGEST;
GRANT USAGE ON WAREHOUSE CRICKET_ETL_WH TO ROLE ROLE_ETL;
GRANT USAGE ON WAREHOUSE CRICKET_APP_WH TO ROLE ROLE_APP_STREAMLIT;

-- ============================================================
-- Bronze read access
-- ============================================================
GRANT SELECT ON VIEW CRICKET_ANALYTICS.BRONZE.BR_CRICKET_TEAMS TO ROLE ROLE_ETL;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.BRONZE.BR_CRICKET_PLAYERS TO ROLE ROLE_ETL;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.BRONZE.BR_CRICKET_MATCHES TO ROLE ROLE_ETL;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.BRONZE.BR_CRICKET_DELIVERIES TO ROLE ROLE_ETL;

-- ============================================================
-- Silver read access for ETL
-- ============================================================
GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.DIM_DATE TO ROLE ROLE_ETL;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.DIM_TEAM TO ROLE ROLE_ETL;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.DIM_VENUE TO ROLE ROLE_ETL;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.DIM_PLAYER TO ROLE ROLE_ETL;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.DIM_MATCH TO ROLE ROLE_ETL;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.FACT_DELIVERY TO ROLE ROLE_ETL;

-- ============================================================
-- Gold read access for analytics/application roles
-- ============================================================
GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.MATCH_OVERVIEW TO ROLE ROLE_ANALYST;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.MATCH_OVERVIEW TO ROLE ROLE_APP_STREAMLIT;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.PLAYER_INSIGHTS TO ROLE ROLE_ANALYST;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.PLAYER_INSIGHTS TO ROLE ROLE_APP_STREAMLIT;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.TEAM_VENUE_ANALYTICS TO ROLE ROLE_ANALYST;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.TEAM_VENUE_ANALYTICS TO ROLE ROLE_APP_STREAMLIT;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.PHASE_ANALYTICS TO ROLE ROLE_ANALYST;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.PHASE_ANALYTICS TO ROLE ROLE_APP_STREAMLIT;

-- ============================================================
-- DW compatibility views
-- ============================================================
GRANT SELECT ON VIEW CRICKET_ANALYTICS.DW.DIM_DATE TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.DW.DIM_TEAM TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.DW.DIM_VENUE TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.DW.DIM_PLAYER TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.DW.DIM_MATCH TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.DW.FACT_DELIVERY TO ROLE ROLE_ANALYST;

-- ============================================================
-- Semantic views
-- ============================================================
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_MATCH_SUMMARY TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_MATCH_SUMMARY TO ROLE ROLE_APP_STREAMLIT;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_PLAYER_BATTING TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_PLAYER_BATTING TO ROLE ROLE_APP_STREAMLIT;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_PLAYER_BOWLING TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_PLAYER_BOWLING TO ROLE ROLE_APP_STREAMLIT;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_TEAM_TRENDS TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_TEAM_TRENDS TO ROLE ROLE_APP_STREAMLIT;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_VENUE_TRENDS TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_VENUE_TRENDS TO ROLE ROLE_APP_STREAMLIT;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_DELIVERY_EXPLORER TO ROLE ROLE_ANALYST;
GRANT SELECT ON VIEW CRICKET_ANALYTICS.SEM.V_DELIVERY_EXPLORER TO ROLE ROLE_APP_STREAMLIT;

-- ============================================================
-- OPS access
-- ============================================================
GRANT SELECT ON TABLE CRICKET_ANALYTICS.OPS.LOAD_AUDIT TO ROLE ROLE_ADMIN;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.OPS.REJECTS TO ROLE ROLE_ADMIN;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.OPS.QUARANTINE_AUDIT TO ROLE ROLE_ADMIN;

-- ============================================================
-- Streamlit owner-rights dependencies
-- ============================================================
-- The validated Streamlit application is owned by ACCOUNTADMIN and
-- executes semantic views with owner's rights. Grant the owner role
-- read access to the underlying analytical tables required by those views.
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.SILVER TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA CRICKET_ANALYTICS.GOLD TO ROLE ACCOUNTADMIN;

GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.DIM_DATE TO ROLE ACCOUNTADMIN;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.DIM_TEAM TO ROLE ACCOUNTADMIN;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.DIM_VENUE TO ROLE ACCOUNTADMIN;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.DIM_PLAYER TO ROLE ACCOUNTADMIN;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.DIM_MATCH TO ROLE ACCOUNTADMIN;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.SILVER.FACT_DELIVERY TO ROLE ACCOUNTADMIN;

GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.MATCH_OVERVIEW TO ROLE ACCOUNTADMIN;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.PLAYER_INSIGHTS TO ROLE ACCOUNTADMIN;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.TEAM_VENUE_ANALYTICS TO ROLE ACCOUNTADMIN;
GRANT SELECT ON TABLE CRICKET_ANALYTICS.GOLD.PHASE_ANALYTICS TO ROLE ACCOUNTADMIN;

-- RAW is intentionally not granted to analyst/application roles.
-- The current cricket feeds contain no PII/PHI, so no masking policy
-- is required for the supplied dataset.