-- 07_security.sql
USE DATABASE CRICKET_ANALYTICS;
CREATE ROLE IF NOT EXISTS ROLE_INGEST;
CREATE ROLE IF NOT EXISTS ROLE_ETL;
CREATE ROLE IF NOT EXISTS ROLE_ANALYST;
CREATE ROLE IF NOT EXISTS ROLE_APP_STREAMLIT;
CREATE ROLE IF NOT EXISTS ROLE_ADMIN;
GRANT USAGE ON DATABASE CRICKET_ANALYTICS TO ROLE_INGEST,ROLE_ETL,ROLE_ANALYST,ROLE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA RAW TO ROLE_INGEST,ROLE_ETL;
GRANT USAGE ON SCHEMA DW TO ROLE_ETL,ROLE_ANALYST,ROLE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA SEM TO ROLE_ANALYST,ROLE_APP_STREAMLIT;
GRANT USAGE ON SCHEMA OPS TO ROLE_ETL,ROLE_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA SEM TO ROLE_ANALYST,ROLE_APP_STREAMLIT;
-- RAW is intentionally not granted to analyst/app roles. Apply masking/row access policies to any PII/PHI columns if introduced.
