-- 08_dq_ops.sql
USE DATABASE CRICKET_ANALYTICS;
CREATE TABLE IF NOT EXISTS OPS.LOAD_AUDIT (BATCH_ID VARCHAR,ENTITY VARCHAR,LOAD_TS TIMESTAMP_LTZ,SOURCE_FILE VARCHAR,SOURCE_ROW_COUNT NUMBER,RAW_ROW_COUNT NUMBER,DW_ROW_COUNT NUMBER,REJECT_COUNT NUMBER,STATUS VARCHAR,MESSAGE VARCHAR);
CREATE TABLE IF NOT EXISTS OPS.REJECTS (REJECT_TS TIMESTAMP_LTZ,BATCH_ID VARCHAR,ENTITY VARCHAR,SOURCE_FILE VARCHAR,ROW_NUMBER NUMBER,REASON VARCHAR,RAW_RECORD VARIANT);

-- Duplicate delivery check
SELECT DELIVERY_ID,COUNT(*) CNT FROM DW.FACT_DELIVERY GROUP BY DELIVERY_ID HAVING COUNT(*)>1;
-- Delivery reference check
SELECT f.DELIVERY_ID FROM DW.FACT_DELIVERY f JOIN DW.DIM_PLAYER p ON f.SK_STRIKER=p.SK_PLAYER WHERE p.PLAYER_ID='UNKNOWN';
-- Delivery run/wicket totals
SELECT MATCH_ID,SUM(TOTAL_RUNS) DELIVERY_RUNS,SUM(IS_WICKET) DELIVERY_WICKETS FROM SEM.V_DELIVERY_EXPLORER GROUP BY MATCH_ID;
-- Ball/over completeness is validated against feed rules; wides/no-balls are not falsely treated as missing legal balls.
-- Match-summary reconciliation is NOT_AVAILABLE for the supplied source because the match feed has no score-summary totals.
-- COPY_HISTORY and VALIDATE are used to identify Snowpipe load errors and feed OPS.REJECTS/quarantine.
