-- 09_dq_quarantine.sql
-- Post-ingestion validation and operational quarantine helpers.
USE DATABASE CRICKET_ANALYTICS;

CREATE TABLE IF NOT EXISTS OPS.REJECTS (
    REJECT_TS TIMESTAMP_LTZ,
    BATCH_ID VARCHAR,
    ENTITY VARCHAR,
    SOURCE_FILE VARCHAR,
    ROW_NUMBER NUMBER,
    REASON VARCHAR,
    RAW_RECORD VARIANT
);

CREATE TABLE IF NOT EXISTS OPS.QUARANTINE_AUDIT (
    QUARANTINE_TS TIMESTAMP_LTZ,
    SOURCE_FILE VARCHAR,
    ENTITY VARCHAR,
    REASON VARCHAR,
    STATUS VARCHAR
);

-- Business-key and referential checks are captured in OPS.REJECTS.
INSERT INTO OPS.REJECTS
SELECT CURRENT_TIMESTAMP(), 'MANUAL_VALIDATION', 'TEAMS', FILE_NAME, ROW_NUMBER,
       'Missing TEAM_ID', OBJECT_CONSTRUCT_KEEP_NULL(*)
FROM RAW.RAW_TEAMS
WHERE TEAM_ID IS NULL;

INSERT INTO OPS.REJECTS
SELECT CURRENT_TIMESTAMP(), 'MANUAL_VALIDATION', 'PLAYERS', FILE_NAME, ROW_NUMBER,
       'Missing PLAYER_ID', OBJECT_CONSTRUCT_KEEP_NULL(*)
FROM RAW.RAW_PLAYERS
WHERE PLAYER_ID IS NULL;

INSERT INTO OPS.REJECTS
SELECT CURRENT_TIMESTAMP(), 'MANUAL_VALIDATION', 'MATCHES', FILE_NAME, ROW_NUMBER,
       'Missing MATCH_ID', OBJECT_CONSTRUCT_KEEP_NULL(*)
FROM RAW.RAW_MATCHES
WHERE MATCH_ID IS NULL;

INSERT INTO OPS.REJECTS
SELECT CURRENT_TIMESTAMP(), 'MANUAL_VALIDATION', 'DELIVERIES', FILE_NAME, ROW_NUMBER,
       'Missing DELIVERY_ID', OBJECT_CONSTRUCT_KEEP_NULL(*)
FROM RAW.RAW_DELIVERIES
WHERE DELIVERY_ID IS NULL;

-- Referential integrity checks.
INSERT INTO OPS.REJECTS
SELECT CURRENT_TIMESTAMP(), 'MANUAL_VALIDATION', 'DELIVERIES', f.FILE_NAME, f.ROW_NUMBER,
       'Unknown MATCH_ID', OBJECT_CONSTRUCT_KEEP_NULL(f.*)
FROM RAW.RAW_DELIVERIES f
LEFT JOIN RAW.RAW_MATCHES m ON m.MATCH_ID = f.MATCH_ID
WHERE f.MATCH_ID IS NOT NULL AND m.MATCH_ID IS NULL;

INSERT INTO OPS.REJECTS
SELECT CURRENT_TIMESTAMP(), 'MANUAL_VALIDATION', 'DELIVERIES', f.FILE_NAME, f.ROW_NUMBER,
       'TOTAL_RUNS reconciliation failed', OBJECT_CONSTRUCT_KEEP_NULL(f.*)
FROM RAW.RAW_DELIVERIES f
WHERE COALESCE(f.TOTAL_RUNS,0) <> COALESCE(f.BATSMAN_RUNS,0)
    + COALESCE(f.WIDES,0)
    + COALESCE(f.NO_BALLS,0)
    + COALESCE(f.BYES,0)
    + COALESCE(f.LEG_BYES,0);

-- File quarantine is deliberately explicit: COPY FILES moves a known bad source
-- file to the quarantine stage after its audit row is recorded.
-- Example:
-- COPY FILES INTO @RAW.CRICKET_QUARANTINE_STAGE
-- FROM @RAW.CRICKET_LANDING_STAGE
-- FILES = ('deliveries/bad_file.csv');
