USE DATABASE CRICKET_ANALYTICS_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE CRICKET_ANALYTICS_STAGE
  FILE_FORMAT = FF_CRICKET_CSV;

-- Upload files using Snowsight or PUT from a Snowflake-compatible client.
-- Expected paths:
-- @CRICKET_ANALYTICS_STAGE/teams/
-- @CRICKET_ANALYTICS_STAGE/players/
-- @CRICKET_ANALYTICS_STAGE/matches/
-- @CRICKET_ANALYTICS_STAGE/deliveries/
