USE DATABASE CRICKET_ANALYTICS_DB;
USE SCHEMA RAW;

-- Safe manual-load pattern for the current internal-stage implementation.
-- Metadata columns are populated separately so source traceability is retained.

COPY INTO RAW_TEAMS
  (TEAM_ID,TEAM_NAME,TEAM_CODE,COUNTRY,COMPETITION,REGION,ESTABLISHED_DATE,STATUS,SOURCE_FILE_NAME)
FROM (
  SELECT $1,$2,$3,$4,$5,$6,TRY_TO_DATE($7),$8,METADATA$FILENAME
  FROM @CRICKET_ANALYTICS_STAGE/teams/
)
FILE_FORMAT=(FORMAT_NAME='FF_CRICKET_CSV')
ON_ERROR='CONTINUE';

COPY INTO RAW_PLAYERS
  (PLAYER_ID,FIRST_NAME,LAST_NAME,NATIONALITY,BATTING_STYLE,BOWLING_STYLE,ROLE,CURRENT_TEAM_ID,CONTRACT_START,STATUS,UPDATED_AT,SOURCE_FILE_NAME)
FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7,$8,TRY_TO_DATE($9),$10,TRY_TO_TIMESTAMP_NTZ($11),METADATA$FILENAME
  FROM @CRICKET_ANALYTICS_STAGE/players/
)
FILE_FORMAT=(FORMAT_NAME='FF_CRICKET_CSV')
ON_ERROR='CONTINUE';

COPY INTO RAW_MATCHES
  (MATCH_ID,COMPETITION,FORMAT,MATCH_DATE,VENUE_ID,TEAM_A_ID,TEAM_B_ID,TOSS_WINNER_TEAM_ID,TOSS_DECISION,WINNER_TEAM_ID,RESULT_TYPE,RESULT_MARGIN,MATCH_STATUS,UPDATED_AT,SOURCE_FILE_NAME)
FROM (
  SELECT $1,$2,$3,TRY_TO_DATE($4),$5,$6,$7,$8,$9,$10,$11,TRY_TO_NUMBER($12),$13,TRY_TO_TIMESTAMP_NTZ($14),METADATA$FILENAME
  FROM @CRICKET_ANALYTICS_STAGE/matches/
)
FILE_FORMAT=(FORMAT_NAME='FF_CRICKET_CSV')
ON_ERROR='CONTINUE';

COPY INTO RAW_DELIVERIES
  (DELIVERY_ID,MATCH_ID,INNINGS_NO,OVER_NO,BALL_NO,BATTING_TEAM_ID,BOWLING_TEAM_ID,STRIKER_PLAYER_ID,NON_STRIKER_PLAYER_ID,BOWLER_PLAYER_ID,BATSMAN_RUNS,WIDES,NO_BALLS,BYES,LEG_BYES,TOTAL_RUNS,IS_WICKET,DISMISSAL_TYPE,IS_FOUR,IS_SIX,IS_DOT_BALL,UPDATED_AT,SOURCE_FILE_NAME)
FROM (
  SELECT $1,$2,TRY_TO_NUMBER($3),TRY_TO_NUMBER($4),TRY_TO_NUMBER($5),$6,$7,$8,$9,$10,
         TRY_TO_NUMBER($11),TRY_TO_NUMBER($12),TRY_TO_NUMBER($13),TRY_TO_NUMBER($14),
         TRY_TO_NUMBER($15),TRY_TO_NUMBER($16),TRY_TO_NUMBER($17),$18,
         TRY_TO_NUMBER($19),TRY_TO_NUMBER($20),TRY_TO_NUMBER($21),
         TRY_TO_TIMESTAMP_NTZ($22),METADATA$FILENAME
  FROM @CRICKET_ANALYTICS_STAGE/deliveries/
)
FILE_FORMAT=(FORMAT_NAME='FF_CRICKET_CSV')
ON_ERROR='CONTINUE';
